hyperparameters:
  batch_size: 96
  discount_factor: 0.95
  interpolation_parameter: 0.005
  learning_freqency: 16
  learning_rate: 0.0015
  replay_buffer_size: 100000
network:
  activation: Custom
  hidden_layers:
  - 32
  - 32
  - 128
  output_activation: Custom
  seed: 42
