hyperparameters:
  batch_size: 64
  discount_factor: 0.95
  interpolation_parameter: 0.005
  learning_freqency: 16
  learning_rate: 0.0005
  replay_buffer_size: 100000
network:
  activation: ReLU
  hidden_layers:
  - 32
  - 256
  output_activation: Softmax
  seed: 42
