hyperparameters:
  batch_size: 128
  discount_factor: 0.95
  interpolation_parameter: 0.001
  learning_freqency: 16
  learning_rate: 0.0005
  replay_buffer_size: 100000
network:
  activation: ReLU
  hidden_layers:
  - 32
  - 64
  - 32
  output_activation: Softmax
  seed: 42
