hyperparameters:
  batch_size: 128
  discount_factor: 0.99
  interpolation_parameter: 0.025
  learning_freqency: 4
  learning_rate: 0.0005
  replay_buffer_size: 100000
network:
  activation: Custom
  hidden_layers:
  - 32
  - 64
  - 32
  output_activation: Custom
  seed: 42
