network:
  seed: 42
  hidden_layers:
    - 64
    - 64
  activation: "ReLU"
  output_activation: "Softmax"

hyperparameters:
  batch_size: 2048
  max_timesteps_per_episode: 200
  discount_factor: 0.99
  n_updates_per_iteration: 10
  learning_rate: 0.0003
  clip: 0.2
  render: False
  render_every_i: 10
