network:
  seed: 42
  hidden_layers:
    - 64
    - 64
  activation: "ReLU"
  output_activation: "Softmax"

hyperparameters:
  learning_rate: 0.001
  discount_factor: 0.99
  batch_size: 32
  learning_rate: 0.0005
  batch_size: 100
  discount_factor: 0.99
  replay_buffer_size: 100000
  interpolation_parameter: 0.001