hyperparameters:
  batch_size: 256
  discount_factor: 0.95
  interpolation_parameter: 0.001
  learning_rate: 0.0015
  replay_buffer_size: 100000
network:
  activation: ReLU
  hidden_layers:
    - 64
    - 64
  output_activation: Softmax
  seed: 42
