hyperparameters:
  batch_size: 96
  discount_factor: 0.95
  interpolation_parameter: 0.005
  learning_freqency: 16
  learning_rate: 0.0015
  replay_buffer_size: 100000
network:
  activation: ReLU
  hidden_layers:
  - 256
  - 128
  - 256
  output_activation: Softmax
  seed: 42
