hyperparameters:
  batch_size: 100
  discount_factor: 0.99
  interpolation_parameter: 0.001
  learning_freqency: 4
  learning_rate: 0.0005
  replay_buffer_size: 100000
network:
  activation: ReLU
  hidden_layers:
  - 64
  - 64
  output_activation: Softmax
  seed: 42
